/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202309GetGMVTrendPerformancesResponseDataGmvTrendPerformances } from './GetGMVTrendPerformancesResponseDataGmvTrendPerformances';

export class Analytics202309GetGMVTrendPerformancesResponseData {
    /**
    * The trend of GMV chart 
    */
    'gmvTrendPerformances'?: Array<Analytics202309GetGMVTrendPerformancesResponseDataGmvTrendPerformances>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "gmvTrendPerformances",
            "baseName": "gmv_trend_performances",
            "type": "Array<Analytics202309GetGMVTrendPerformancesResponseDataGmvTrendPerformances>"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202309GetGMVTrendPerformancesResponseData.attributeTypeMap;
    }
}

