/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202309GetInteractiveTrendPerformancesResponseDataInteractiveTrendPerformances } from './GetInteractiveTrendPerformancesResponseDataInteractiveTrendPerformances';

export class Analytics202309GetInteractiveTrendPerformancesResponseData {
    /**
    * The trend data of living room
    */
    'interactiveTrendPerformances'?: Array<Analytics202309GetInteractiveTrendPerformancesResponseDataInteractiveTrendPerformances>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "interactiveTrendPerformances",
            "baseName": "interactive_trend_performances",
            "type": "Array<Analytics202309GetInteractiveTrendPerformancesResponseDataInteractiveTrendPerformances>"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202309GetInteractiveTrendPerformancesResponseData.attributeTypeMap;
    }
}

