/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202309GetProductStatsResponseDataProductStats } from './GetProductStatsResponseDataProductStats';

export class Analytics202309GetProductStatsResponseData {
    /**
    * The stats of the live streaming room, e.g. GMV
    */
    'productStats'?: Array<Analytics202309GetProductStatsResponseDataProductStats>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "productStats",
            "baseName": "product_stats",
            "type": "Array<Analytics202309GetProductStatsResponseDataProductStats>"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202309GetProductStatsResponseData.attributeTypeMap;
    }
}

