/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202309GetUserPortraitsResponseDataAllAdsAgeIndicators } from './GetUserPortraitsResponseDataAllAdsAgeIndicators';
import { Analytics202309GetUserPortraitsResponseDataAllAdsGenderIndicators } from './GetUserPortraitsResponseDataAllAdsGenderIndicators';
import { Analytics202309GetUserPortraitsResponseDataAllFanIndicators } from './GetUserPortraitsResponseDataAllFanIndicators';
import { Analytics202309GetUserPortraitsResponseDataPaidAdsAgeIndicators } from './GetUserPortraitsResponseDataPaidAdsAgeIndicators';
import { Analytics202309GetUserPortraitsResponseDataPaidAdsGenderIndicators } from './GetUserPortraitsResponseDataPaidAdsGenderIndicators';
import { Analytics202309GetUserPortraitsResponseDataPaidFanIndicators } from './GetUserPortraitsResponseDataPaidFanIndicators';
import { Analytics202309GetUserPortraitsResponseDataRegionIndicators } from './GetUserPortraitsResponseDataRegionIndicators';

export class Analytics202309GetUserPortraitsResponseData {
    /**
    * Age indicators for advertisement
    */
    'allAdsAgeIndicators'?: Array<Analytics202309GetUserPortraitsResponseDataAllAdsAgeIndicators>;
    /**
    * Gender indicators for advertisement
    */
    'allAdsGenderIndicators'?: Array<Analytics202309GetUserPortraitsResponseDataAllAdsGenderIndicators>;
    /**
    * Fans indicators
    */
    'allFanIndicators'?: Array<Analytics202309GetUserPortraitsResponseDataAllFanIndicators>;
    /**
    * Paid advertisement age indicators for advertisement
    */
    'paidAdsAgeIndicators'?: Array<Analytics202309GetUserPortraitsResponseDataPaidAdsAgeIndicators>;
    /**
    * Paid advertisement gender indicators for advertisement
    */
    'paidAdsGenderIndicators'?: Array<Analytics202309GetUserPortraitsResponseDataPaidAdsGenderIndicators>;
    /**
    * Paid fans indicators
    */
    'paidFanIndicators'?: Array<Analytics202309GetUserPortraitsResponseDataPaidFanIndicators>;
    /**
    * Region indicators
    */
    'regionIndicators'?: Array<Analytics202309GetUserPortraitsResponseDataRegionIndicators>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "allAdsAgeIndicators",
            "baseName": "all_ads_age_indicators",
            "type": "Array<Analytics202309GetUserPortraitsResponseDataAllAdsAgeIndicators>"
        },
        {
            "name": "allAdsGenderIndicators",
            "baseName": "all_ads_gender_indicators",
            "type": "Array<Analytics202309GetUserPortraitsResponseDataAllAdsGenderIndicators>"
        },
        {
            "name": "allFanIndicators",
            "baseName": "all_fan_indicators",
            "type": "Array<Analytics202309GetUserPortraitsResponseDataAllFanIndicators>"
        },
        {
            "name": "paidAdsAgeIndicators",
            "baseName": "paid_ads_age_indicators",
            "type": "Array<Analytics202309GetUserPortraitsResponseDataPaidAdsAgeIndicators>"
        },
        {
            "name": "paidAdsGenderIndicators",
            "baseName": "paid_ads_gender_indicators",
            "type": "Array<Analytics202309GetUserPortraitsResponseDataPaidAdsGenderIndicators>"
        },
        {
            "name": "paidFanIndicators",
            "baseName": "paid_fan_indicators",
            "type": "Array<Analytics202309GetUserPortraitsResponseDataPaidFanIndicators>"
        },
        {
            "name": "regionIndicators",
            "baseName": "region_indicators",
            "type": "Array<Analytics202309GetUserPortraitsResponseDataRegionIndicators>"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202309GetUserPortraitsResponseData.attributeTypeMap;
    }
}

