/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202309GetViewTrendPerformancesResponseDataViewTrendPerformances } from './GetViewTrendPerformancesResponseDataViewTrendPerformances';

export class Analytics202309GetViewTrendPerformancesResponseData {
    /**
    * Viewer count trends of the live streaming room
    */
    'viewTrendPerformances'?: Array<Analytics202309GetViewTrendPerformancesResponseDataViewTrendPerformances>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "viewTrendPerformances",
            "baseName": "view_trend_performances",
            "type": "Array<Analytics202309GetViewTrendPerformancesResponseDataViewTrendPerformances>"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202309GetViewTrendPerformancesResponseData.attributeTypeMap;
    }
}

