/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202502GetGMVTrendPerformancesResponseDataGmvTrendPerformancesDataPoints } from './GetGMVTrendPerformancesResponseDataGmvTrendPerformancesDataPoints';

export class Analytics202502GetGMVTrendPerformancesResponseDataGmvTrendPerformances {
    /**
    * The data point of GMV trend 
    */
    'dataPoints'?: Array<Analytics202502GetGMVTrendPerformancesResponseDataGmvTrendPerformancesDataPoints>;
    /**
    * The stats_type describes the type of value below.  TREND_GMV :the GMV of the live streaming room  TREND_CREATED_ORDER : the order created in the live streaming room
    */
    'statsType'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dataPoints",
            "baseName": "data_points",
            "type": "Array<Analytics202502GetGMVTrendPerformancesResponseDataGmvTrendPerformancesDataPoints>"
        },
        {
            "name": "statsType",
            "baseName": "stats_type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202502GetGMVTrendPerformancesResponseDataGmvTrendPerformances.attributeTypeMap;
    }
}

