/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Analytics202502GetUserPortraitsResponseDataAllAdsAgeIndicators } from './GetUserPortraitsResponseDataAllAdsAgeIndicators';
import { Analytics202502GetUserPortraitsResponseDataAllAdsGenderIndicators } from './GetUserPortraitsResponseDataAllAdsGenderIndicators';
import { Analytics202502GetUserPortraitsResponseDataAllFanIndicators } from './GetUserPortraitsResponseDataAllFanIndicators';
import { Analytics202502GetUserPortraitsResponseDataPaidAdsAgeIndicators } from './GetUserPortraitsResponseDataPaidAdsAgeIndicators';
import { Analytics202502GetUserPortraitsResponseDataPaidAdsGenderIndicators } from './GetUserPortraitsResponseDataPaidAdsGenderIndicators';
import { Analytics202502GetUserPortraitsResponseDataPaidFanIndicators } from './GetUserPortraitsResponseDataPaidFanIndicators';
import { Analytics202502GetUserPortraitsResponseDataRegionIndicators } from './GetUserPortraitsResponseDataRegionIndicators';

export class Analytics202502GetUserPortraitsResponseData {
    /**
    * Age indicators for advertisement
    */
    'allAdsAgeIndicators'?: Array<Analytics202502GetUserPortraitsResponseDataAllAdsAgeIndicators>;
    /**
    * Gender indicators for advertisement
    */
    'allAdsGenderIndicators'?: Array<Analytics202502GetUserPortraitsResponseDataAllAdsGenderIndicators>;
    /**
    * Fans indicators
    */
    'allFanIndicators'?: Array<Analytics202502GetUserPortraitsResponseDataAllFanIndicators>;
    /**
    * Paid advertisement age indicators for advertisement
    */
    'paidAdsAgeIndicators'?: Array<Analytics202502GetUserPortraitsResponseDataPaidAdsAgeIndicators>;
    /**
    * Paid advertisement gender indicators for advertisement
    */
    'paidAdsGenderIndicators'?: Array<Analytics202502GetUserPortraitsResponseDataPaidAdsGenderIndicators>;
    /**
    * Paid fans indicators
    */
    'paidFanIndicators'?: Array<Analytics202502GetUserPortraitsResponseDataPaidFanIndicators>;
    /**
    * Region indicators
    */
    'regionIndicators'?: Array<Analytics202502GetUserPortraitsResponseDataRegionIndicators>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "allAdsAgeIndicators",
            "baseName": "all_ads_age_indicators",
            "type": "Array<Analytics202502GetUserPortraitsResponseDataAllAdsAgeIndicators>"
        },
        {
            "name": "allAdsGenderIndicators",
            "baseName": "all_ads_gender_indicators",
            "type": "Array<Analytics202502GetUserPortraitsResponseDataAllAdsGenderIndicators>"
        },
        {
            "name": "allFanIndicators",
            "baseName": "all_fan_indicators",
            "type": "Array<Analytics202502GetUserPortraitsResponseDataAllFanIndicators>"
        },
        {
            "name": "paidAdsAgeIndicators",
            "baseName": "paid_ads_age_indicators",
            "type": "Array<Analytics202502GetUserPortraitsResponseDataPaidAdsAgeIndicators>"
        },
        {
            "name": "paidAdsGenderIndicators",
            "baseName": "paid_ads_gender_indicators",
            "type": "Array<Analytics202502GetUserPortraitsResponseDataPaidAdsGenderIndicators>"
        },
        {
            "name": "paidFanIndicators",
            "baseName": "paid_fan_indicators",
            "type": "Array<Analytics202502GetUserPortraitsResponseDataPaidFanIndicators>"
        },
        {
            "name": "regionIndicators",
            "baseName": "region_indicators",
            "type": "Array<Analytics202502GetUserPortraitsResponseDataRegionIndicators>"
        }    ];

    static getAttributeTypeMap() {
        return Analytics202502GetUserPortraitsResponseData.attributeTypeMap;
    }
}

